/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendingmachine12;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jdk.nashorn.internal.runtime.NumberToString;

/**
 *
 * @author User
 */
public class Machine extends javax.swing.JFrame {

    /**
     * Creates new form Machine
     */
    public Machine() {
        initComponents();
          getContentPane().setBackground(Color.pink);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        kurkure1 = new javax.swing.JRadioButton();
        kitkat2 = new javax.swing.JRadioButton();
        layscream3 = new javax.swing.JRadioButton();
        burbun5 = new javax.swing.JRadioButton();
        cadbury6 = new javax.swing.JRadioButton();
        moongdal7 = new javax.swing.JRadioButton();
        mirinda4 = new javax.swing.JRadioButton();
        laysclassic8 = new javax.swing.JRadioButton();
        kurkure = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancle = new javax.swing.JButton();
        plmoney = new javax.swing.JLabel();
        insertmoney = new javax.swing.JTextField();
        change = new javax.swing.JTextField();
        kitkat = new javax.swing.JButton();
        layscream = new javax.swing.JButton();
        mirinda = new javax.swing.JButton();
        burbun = new javax.swing.JButton();
        cadbury = new javax.swing.JButton();
        moongdal = new javax.swing.JButton();
        laysclassic = new javax.swing.JButton();
        changebtn = new javax.swing.JButton();
        remainingbalance = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("    Vending Machine");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("select an item"));

        kurkure1.setText("Kurkure  RS.10");
        kurkure1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurkure1ActionPerformed(evt);
            }
        });

        kitkat2.setText("Kitkat  RS.20");
        kitkat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitkat2ActionPerformed(evt);
            }
        });

        layscream3.setText("Lays cream and onion flavour  RS.10");
        layscream3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layscream3ActionPerformed(evt);
            }
        });

        burbun5.setText("Burbun RS.10");
        burbun5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burbun5ActionPerformed(evt);
            }
        });

        cadbury6.setText("Cadbury RS.20");
        cadbury6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadbury6ActionPerformed(evt);
            }
        });

        moongdal7.setText("Moong Dal RS.10");
        moongdal7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moongdal7ActionPerformed(evt);
            }
        });

        mirinda4.setText("Mirinda  RS. 20");
        mirinda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirinda4ActionPerformed(evt);
            }
        });

        laysclassic8.setText("Lays Classic RS.10");
        laysclassic8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laysclassic8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kurkure1)
                    .addComponent(burbun5))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitkat2)
                    .addComponent(cadbury6))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layscream3)
                    .addComponent(moongdal7))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laysclassic8)
                    .addComponent(mirinda4))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kurkure1)
                    .addComponent(kitkat2)
                    .addComponent(layscream3)
                    .addComponent(mirinda4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burbun5)
                    .addComponent(cadbury6)
                    .addComponent(moongdal7)
                    .addComponent(laysclassic8))
                .addGap(15, 15, 15))
        );

        kurkure.setText("Kurkure");
        kurkure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurkureActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        cancle.setText("Cancle");
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });

        plmoney.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        plmoney.setText("Please insert your money :");

        insertmoney.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insertmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertmoneyActionPerformed(evt);
            }
        });
        insertmoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                insertmoneyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                insertmoneyKeyTyped(evt);
            }
        });

        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });

        kitkat.setText("Kitkat");
        kitkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitkatActionPerformed(evt);
            }
        });

        layscream.setText("Lays cream and onion ");
        layscream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layscreamActionPerformed(evt);
            }
        });

        mirinda.setText("Mirinda");
        mirinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirindaActionPerformed(evt);
            }
        });

        burbun.setText("Burbun");
        burbun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burbunActionPerformed(evt);
            }
        });

        cadbury.setText("Cadbury");
        cadbury.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadburyActionPerformed(evt);
            }
        });

        moongdal.setText("Moong Dal");
        moongdal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moongdalActionPerformed(evt);
            }
        });

        laysclassic.setText("Lays Classic");
        laysclassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laysclassicActionPerformed(evt);
            }
        });

        changebtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        changebtn.setText("Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });

        remainingbalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        remainingbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainingbalanceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Available balance :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kurkure)
                            .addComponent(burbun))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cadbury)
                            .addComponent(kitkat)
                            .addComponent(clear))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(moongdal)
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mirinda)
                                            .addComponent(laysclassic)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(layscream))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(changebtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(plmoney))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(insertmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remainingbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remainingbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plmoney)
                    .addComponent(insertmoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changebtn)
                    .addComponent(change, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kurkure)
                    .addComponent(kitkat)
                    .addComponent(layscream)
                    .addComponent(mirinda))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(burbun)
                    .addComponent(cadbury)
                    .addComponent(moongdal)
                    .addComponent(laysclassic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(cancle))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitkat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitkat2ActionPerformed
        // TODO add your handling code here:
         if(kitkat2.isSelected()){
        kurkure1.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        }
         if(kitkat2.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(true);
         layscream.setEnabled(false);
         mirinda.setEnabled(false);
         burbun.setEnabled(false);
         cadbury.setEnabled(false);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(false);
         }
        
     
         
    }//GEN-LAST:event_kitkat2ActionPerformed

    private void layscream3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layscream3ActionPerformed
        // TODO add your handling code here:
         if(layscream3.isSelected()){
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        }
         if(layscream3.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(false);
         layscream.setEnabled(true);
         mirinda.setEnabled(false);
         burbun.setEnabled(false);
         cadbury.setEnabled(false);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(false);
          }
    }//GEN-LAST:event_layscream3ActionPerformed

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // cancle selection
        System.exit(0);
    }//GEN-LAST:event_cancleActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // clear all selection
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        remainingbalance.setText(" ");
        insertmoney.setText(" ");
        change.setText(" ");
        kurkure.setEnabled(true);
         kitkat.setEnabled(true);
         layscream.setEnabled(true);
         mirinda.setEnabled(true);
         burbun.setEnabled(true);
         cadbury.setEnabled(true);
         moongdal.setEnabled(true);
         laysclassic.setEnabled(true);
      remainingbalance.setEnabled(true);
        
    }//GEN-LAST:event_clearActionPerformed

    private void kurkure1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurkure1ActionPerformed
        // TODO add your handling code here:
        if(kurkure1.isSelected()){
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        }
      if(kurkure1.isSelected()){
        kurkure.setEnabled(true);
        kitkat.setEnabled(false);
        layscream.setEnabled(false);
         mirinda.setEnabled(false);
         burbun.setEnabled(false);
         cadbury.setEnabled(false);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(false);
      }
 
    }//GEN-LAST:event_kurkure1ActionPerformed

    private void mirinda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirinda4ActionPerformed
        // TODO add your handling code here:
         if(mirinda4.isSelected()){
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        }
          if(mirinda4.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(false);
         layscream.setEnabled(false);
         mirinda.setEnabled(true);
         burbun.setEnabled(false);
         cadbury.setEnabled(false);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(false);
          }
          
                  
    }//GEN-LAST:event_mirinda4ActionPerformed

    private void burbun5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burbun5ActionPerformed
        // TODO add your handling code here:
         if(burbun5.isSelected()){
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        }
          if(burbun5.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(false);
         layscream.setEnabled(false);
         mirinda.setEnabled(false);
         burbun.setEnabled(true);
         cadbury.setEnabled(false);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(false);
          }
    }//GEN-LAST:event_burbun5ActionPerformed

    private void cadbury6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadbury6ActionPerformed
        // TODO add your handling code here:
         if(cadbury6.isSelected()){
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        moongdal7.setSelected(false);
        laysclassic8.setSelected(false);
        }
          if(cadbury6.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(false);
         layscream.setEnabled(false);
         mirinda.setEnabled(false);
         burbun.setEnabled(false);
         cadbury.setEnabled(true);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(false);
          }
    }//GEN-LAST:event_cadbury6ActionPerformed

    private void moongdal7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moongdal7ActionPerformed
        // TODO add your handling code here:
         if(moongdal7.isSelected()){
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        laysclassic8.setSelected(false);
        }
          if(moongdal7.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(false);
         layscream.setEnabled(false);
         mirinda.setEnabled(false);
         burbun.setEnabled(false);
         cadbury.setEnabled(false);
         moongdal.setEnabled(true);
         laysclassic.setEnabled(false);
          }
    }//GEN-LAST:event_moongdal7ActionPerformed

    private void laysclassic8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laysclassic8ActionPerformed
        // TODO add your handling code here:
         if(laysclassic8.isSelected()){
        kurkure1.setSelected(false);
        kitkat2.setSelected(false);
        layscream3.setSelected(false);
        mirinda4.setSelected(false);
        burbun5.setSelected(false);
        cadbury6.setSelected(false);
        moongdal7.setSelected(false);   
        }
          if(laysclassic8.isSelected()){
         kurkure.setEnabled(false);
         kitkat.setEnabled(false);
         layscream.setEnabled(false);
         mirinda.setEnabled(false);
         burbun.setEnabled(false);
         cadbury.setEnabled(false);
         moongdal.setEnabled(false);
         laysclassic.setEnabled(true);
          }
    
    }//GEN-LAST:event_laysclassic8ActionPerformed

    private void insertmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertmoneyActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_insertmoneyActionPerformed

    private void kurkureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurkureActionPerformed
        // TODO add your handling code here
     
    double price =0;
    double money =0;
        if(kurkure1.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
             insertmoney.setText(Double.toString(0));
               remainingbalance.setText(Double.toString(money));
               remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -10;
               remainingbalance.setText(Double.toString(price));
               remainingbalance.setEditable(false);
              
                kurkure.setEnabled(false);
            }
            
               
           if(price >=0){
                 JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                 JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
                 }
        }
    }//GEN-LAST:event_kurkureActionPerformed

    private void kitkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitkatActionPerformed
        // TODO add your handling code here:
    double price =0;
    double money =0;
        if(kitkat2.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Integer.parseInt(insertmoney.getText());
                money = money -20;
                  insertmoney.setText(Double.toString(0));
                remainingbalance.setText(Double.toString(money));
               remainingbalance.setEditable(false);
                
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -20;
               remainingbalance.setText(Double.toString(price));
                remainingbalance.setEditable(false);
                kitkat.setEnabled(false);
           
            }
               
            if(price >=0){
                   JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                   JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
                 }
        }
    }//GEN-LAST:event_kitkatActionPerformed

    private void layscreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layscreamActionPerformed
        // TODO add your handling code here:
    double price =0;
    double money =0;
        if(layscream3.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
                  insertmoney.setText(Double.toString(0));
               remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -10;
                remainingbalance.setText(Double.toString(price));
              remainingbalance.setEditable(false);
                layscream.setEnabled(false);
            }
            if(price >=0){
                JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
            }
        }
    }//GEN-LAST:event_layscreamActionPerformed

    private void mirindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirindaActionPerformed
        // TODO add your handling code here:
    double price =0;
    double money =0;
        if(mirinda4.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Integer.parseInt(insertmoney.getText());
                money = money -20;
                  insertmoney.setText(Double.toString(0));
                remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -20;
              remainingbalance.setText(Double.toString(price));
               remainingbalance.setEditable(false);
                mirinda.setEnabled(false);
            }
               
            if(price >=0){
                JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
            }
        }
    }//GEN-LAST:event_mirindaActionPerformed

    private void burbunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burbunActionPerformed
        // TODO add your handling code here:
    double price =0;
    double money =0;
        if(burbun5.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Integer.parseInt(insertmoney.getText());
                money = money -10;
                  insertmoney.setText(Double.toString(0));
                remainingbalance.setText(Double.toString(money));
               remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -10;
              remainingbalance.setText(Double.toString(price));
                remainingbalance.setEditable(false);
                burbun.setEnabled(false);
            }
               
            if(price >=0){
                 JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                  JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
            }
        }
    }//GEN-LAST:event_burbunActionPerformed

    private void cadburyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadburyActionPerformed
        // TODO add your handling code here:
    double price =0;
    double money =0;
        if(cadbury6.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Integer.parseInt(insertmoney.getText());
                money = money -20;
                  insertmoney.setText(Double.toString(0));
               remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -20;
                remainingbalance.setText(Double.toString(price));
                remainingbalance.setEditable(false);
                cadbury.setEnabled(false);
            }
            if(price >=0){
                JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
            }
        }
    }//GEN-LAST:event_cadburyActionPerformed

    private void moongdalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moongdalActionPerformed
        // TODO add your handling code here:
    double price =0;
    double money =0;
        if(moongdal7.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Integer.parseInt(insertmoney.getText());
                money = money -10;
                  insertmoney.setText(Double.toString(0));
                remainingbalance.setText(Double.toString(money));
               remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -10;
               remainingbalance.setText(Double.toString(price));
                remainingbalance.setEditable(false);
                moongdal.setEnabled(false);
            }
            if(price >=0){
                JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
            }
        }
    }//GEN-LAST:event_moongdalActionPerformed

    private void laysclassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laysclassicActionPerformed
        // TODO add your handling code here:
     
    double price =0;
    double money =0;
        if(laysclassic8.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Integer.parseInt(insertmoney.getText());
                money = money -10;
                  insertmoney.setText(Double.toString(0));
               remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else  {
                price = Double.parseDouble(remainingbalance.getText());
                price = price -10;
               remainingbalance.setText(Double.toString(price));
                remainingbalance.setEditable(false);
                laysclassic.setEnabled(false);
            }
            if(price >=0){
                JOptionPane.showMessageDialog(insertmoney, "You have  purchase sucessfully");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Sorry  You Do Not Have Enough Money");
            }
          }
    }//GEN-LAST:event_laysclassicActionPerformed

    private void insertmoneyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insertmoneyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_insertmoneyKeyTyped

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        // TODO add your handling code here:
        double money;
     
        double price;
     
     

        if(kurkure1.isSelected()){
            if(remainingbalance.getText().isEmpty()){ 
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
                change.setText(Double.toString(money));
                remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
                remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
                remainingbalance.setText("0");
               remainingbalance.setEditable(false);
                } 
            
        }
         if(kitkat2.isSelected()){
             if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -20;
                change.setText(Double.toString(money));
               remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
               remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
                remainingbalance.setText("0");
                remainingbalance.setEditable(false);
             
                } 
        }
        if(layscream3.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
                change.setText(Double.toString(money));
                remainingbalance.setText(Double.toString(money));
              remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
                remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
               remainingbalance.setText("0");
                remainingbalance.setEditable(false);
        } 
        }
        if(mirinda4.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -20;
                change.setText(Double.toString(money));
               remainingbalance.setText(Double.toString(money));
               remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
                remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
                remainingbalance.setText("0");
                remainingbalance.setEditable(false);
                } 
        }
        if(burbun5.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
                change.setText(Double.toString(money));
                remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
               remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
               remainingbalance.setText("0");
               remainingbalance.setEditable(false); 
                } 
        }
        if(cadbury6.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -20;
                change.setText(Double.toString(money));
                remainingbalance.setText(Double.toString(money));
              remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
                remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
               remainingbalance.setText("0");
              remainingbalance.setEditable(false);
                } 
        }
        if(moongdal7.isSelected()){
             if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
                change.setText(Double.toString(money));
               remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
                remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
                remainingbalance.setText("0");
                remainingbalance.setEditable(false);
                
                } 
        }
        if(laysclassic8.isSelected()){
            if(remainingbalance.getText().isEmpty()){
                money = Double.parseDouble(insertmoney.getText());
                money = money -10;
                change.setText(Double.toString(money));
               remainingbalance.setText(Double.toString(money));
                remainingbalance.setEditable(false);
            }else {
                price = Double.parseDouble(remainingbalance.getText());
               remainingbalance.setText(Double.toString(price));
                change.setText(Double.toString(price));
               
                remainingbalance.setText("0");
               remainingbalance.setEditable(false);
               } 
        }
    }//GEN-LAST:event_changebtnActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        
   
    }//GEN-LAST:event_changeActionPerformed

    private void insertmoneyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insertmoneyKeyPressed
        // TODO add your handling code here:
     String plmoney = insertmoney.getText();
        int length = plmoney.length();
         char c = evt.getKeyChar();
          if(evt.getKeyChar() >= '0' && evt.getKeyChar() <='5') {
              if(length < 2) {
              insertmoney.setEditable(true);
           } 
              else{
                 insertmoney.setEditable(false);
              } 
       }else{
                      if(evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                   insertmoney.setEditable(true);
                      }
                      else{
                      insertmoney.setEditable(false);
                      }
                      }
             
         
       int noteinsert=0;
       
       while (noteinsert ==10 || noteinsert == 20 || noteinsert == 50 ){
            if(noteinsert == 10){
            JOptionPane.showMessageDialog(insertmoney, "its valid");
            }else if(noteinsert == 20){
            JOptionPane.showMessageDialog(insertmoney, "its valid");
            }else if(noteinsert == 50){
            JOptionPane.showMessageDialog(insertmoney, "its valid");
            }else{
            JOptionPane.showMessageDialog(insertmoney, "its not valid");
            }
        }
    }//GEN-LAST:event_insertmoneyKeyPressed

    private void remainingbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainingbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainingbalanceActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Machine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Machine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton burbun;
    private javax.swing.JRadioButton burbun5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadbury;
    private javax.swing.JRadioButton cadbury6;
    private javax.swing.JButton cancle;
    private javax.swing.JTextField change;
    private javax.swing.JButton changebtn;
    private javax.swing.JButton clear;
    private javax.swing.JTextField insertmoney;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kitkat;
    private javax.swing.JRadioButton kitkat2;
    private javax.swing.JButton kurkure;
    private javax.swing.JRadioButton kurkure1;
    private javax.swing.JButton laysclassic;
    private javax.swing.JRadioButton laysclassic8;
    private javax.swing.JButton layscream;
    private javax.swing.JRadioButton layscream3;
    private javax.swing.JButton mirinda;
    private javax.swing.JRadioButton mirinda4;
    private javax.swing.JButton moongdal;
    private javax.swing.JRadioButton moongdal7;
    private javax.swing.JLabel plmoney;
    private javax.swing.JTextField remainingbalance;
    // End of variables declaration//GEN-END:variables
}
